version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 manage.py runserver 0.0.0.0:8880'
    volumes:
        - .:/comics
    ports:
        - 8888:8880 